description: RL-Codegen

target:
  service: aml
  # name: V100
  # name: V10032G
  # name: A100EastUS
  # name: openai-A10080G
  # name: A10080G
  # name: gpu-v100-32g
  name: V10032G

#target:
#  service: amlk8s
#  name: itphyperdgxcl1
#  vc: bagaivc

environment:
  image: deepspeed/deepspeed:v0510_torch19_cuda111 # azureml/openmpi4.1.0-cuda11.1-cudnn8-ubuntu18.04 #pytorch/pytorch:1.9.1-cuda11.1-cudnn8-devel
  setup:
    - pip install nvsmi
    - pip install pyext==0.7

storage:
  output:
    storage_account_name: tsinterns
    container_name: t-qingru
    mount_dir: /mnt/t-qingru

code:
  local_dir: ../

jobs:
- name: RL-reward-eval
  sku: 1xG8
  process_count_per_node: 1
  submit_args:
    container_args:
      cpus: 32
  command:
    # Finetuning
    #- python train.py --batch-size-per-replica 3 --grad-acc-steps 4 --epochs 10 --lr 2e-5 --save-freq 1000 --log-freq 10 --save_total_limit 5 --fp16 --tuning_mode none --model codet5-large --train-path /mnt/t-qingru/RLHF/APPS/train/
    #- pip install -r requirements.txt
    - pip install -e transformers/
    - CUDA_VISIBLE_DEVICES=0 python generate.py --model_path /mnt/t-qingru/RLHF/outputs_re/reward_model/base_finetuned_temp0.6_seq20_GT/checkpoint-10000/ --score_name 10000 --test_path /mnt/t-qingru/RLHF/APPS_CRITIC/train/ --output_path /mnt/t-qingru/RLHF/reward_scores_re/finetuned_re_temp0.6_seq20/ --reward_scores -s 0 -e 625 & \
    - CUDA_VISIBLE_DEVICES=1 python generate.py --model_path /mnt/t-qingru/RLHF/outputs_re/reward_model/base_finetuned_temp0.6_seq20_GT/checkpoint-10000/ --score_name 10000 --test_path /mnt/t-qingru/RLHF/APPS_CRITIC/train/ --output_path /mnt/t-qingru/RLHF/reward_scores_re/finetuned_re_temp0.6_seq20/ --reward_scores -s 625 -e 1250 & \
    - CUDA_VISIBLE_DEVICES=2 python generate.py --model_path /mnt/t-qingru/RLHF/outputs_re/reward_model/base_finetuned_temp0.6_seq20_GT/checkpoint-10000/ --score_name 10000 --test_path /mnt/t-qingru/RLHF/APPS_CRITIC/train/ --output_path /mnt/t-qingru/RLHF/reward_scores_re/finetuned_re_temp0.6_seq20/ --reward_scores -s 1250 -e 1875 & \
    - CUDA_VISIBLE_DEVICES=3 python generate.py --model_path /mnt/t-qingru/RLHF/outputs_re/reward_model/base_finetuned_temp0.6_seq20_GT/checkpoint-10000/ --score_name 10000 --test_path /mnt/t-qingru/RLHF/APPS_CRITIC/train/ --output_path /mnt/t-qingru/RLHF/reward_scores_re/finetuned_re_temp0.6_seq20/ --reward_scores -s 1875 -e 2500 & \
    - CUDA_VISIBLE_DEVICES=4 python generate.py --model_path /mnt/t-qingru/RLHF/outputs_re/reward_model/base_finetuned_temp0.6_seq20_GT/checkpoint-10000/ --score_name 10000 --test_path /mnt/t-qingru/RLHF/APPS_CRITIC/train/ --output_path /mnt/t-qingru/RLHF/reward_scores_re/finetuned_re_temp0.6_seq20/ --reward_scores -s 2500 -e 3125 & \
    - CUDA_VISIBLE_DEVICES=5 python generate.py --model_path /mnt/t-qingru/RLHF/outputs_re/reward_model/base_finetuned_temp0.6_seq20_GT/checkpoint-10000/ --score_name 10000 --test_path /mnt/t-qingru/RLHF/APPS_CRITIC/train/ --output_path /mnt/t-qingru/RLHF/reward_scores_re/finetuned_re_temp0.6_seq20/ --reward_scores -s 3125 -e 3750 & \
    - CUDA_VISIBLE_DEVICES=6 python generate.py --model_path /mnt/t-qingru/RLHF/outputs_re/reward_model/base_finetuned_temp0.6_seq20_GT/checkpoint-10000/ --score_name 10000 --test_path /mnt/t-qingru/RLHF/APPS_CRITIC/train/ --output_path /mnt/t-qingru/RLHF/reward_scores_re/finetuned_re_temp0.6_seq20/ --reward_scores -s 3750 -e 4375 & \
    - CUDA_VISIBLE_DEVICES=7 python generate.py --model_path /mnt/t-qingru/RLHF/outputs_re/reward_model/base_finetuned_temp0.6_seq20_GT/checkpoint-10000/ --score_name 10000 --test_path /mnt/t-qingru/RLHF/APPS_CRITIC/train/ --output_path /mnt/t-qingru/RLHF/reward_scores_re/finetuned_re_temp0.6_seq20/ --reward_scores -s 4375 -e 5000
    - sleep 3600
    #    - CUDA_VISIBLE_DEVICES=0 python generate.py --model_path /mnt/t-qingru/RLHF/outputs_re/critic/base_finetuned_temp0.6_seq20_GT/final_checkpoint/ --test_path /mnt/t-qingru/RLHF/APPS_CRITIC/train/ --output_path /mnt/t-qingru/RLHF/critic_scores_re/finetuned_re_temp0.6_seq20/ --critic_scores -s 1000 -e 2000 & \
#    - CUDA_VISIBLE_DEVICES=1 python generate.py --model_path /mnt/t-qingru/RLHF/outputs_re/critic/base_finetuned_temp0.6_seq20_GT/final_checkpoint/ --test_path /mnt/t-qingru/RLHF/APPS_CRITIC/train/ --output_path /mnt/t-qingru/RLHF/critic_scores_re/finetuned_re_temp0.6_seq20/ --critic_scores -s 2000 -e 3000 & \
#    - CUDA_VISIBLE_DEVICES=2 python generate.py --model_path /mnt/t-qingru/RLHF/outputs_re/critic/base_finetuned_temp0.6_seq20_GT/final_checkpoint/ --test_path /mnt/t-qingru/RLHF/APPS_CRITIC/train/ --output_path /mnt/t-qingru/RLHF/critic_scores_re/finetuned_re_temp0.6_seq20/ --critic_scores -s 3000 -e 4000 & \
#    - CUDA_VISIBLE_DEVICES=3 python generate.py --model_path /mnt/t-qingru/RLHF/outputs_re/critic/base_finetuned_temp0.6_seq20_GT/final_checkpoint/ --test_path /mnt/t-qingru/RLHF/APPS_CRITIC/train/ --output_path /mnt/t-qingru/RLHF/critic_scores_re/finetuned_re_temp0.6_seq20/ --critic_scores -s 4000 -e 5000
#    - sleep 7200
    #- deepspeed train.py --batch-size-per-replica 4 --grad-acc-steps 2 --epochs 10 --lr 2e-5 --save-freq 1000 --log-freq 10 --save_total_limit 5 --tuning_mode critic --model codet5-base --fp16 --deepspeed configs/deepspeed_configs.json --train-path /mnt/t-qingru/RLHF/critic_data/APPS_critic_finetuned_2/train/ --save_dir /mnt/t-qingru/RLHF/outputs/critic/base_finetuned_temp0.6_seq20_2/
    #- python train.py --batch-size-per-replica 4 --grad-acc-steps 1 --lr 0.0 --save-freq 1000 --log-freq 10 --save_total_limit 1 --tuning_mode critic --model codet5-base --fp16 --deepspeed configs/deepspeed_configs.json --train-path /mnt/t-qingru/RLHF/critic_data/APPS_critic_finetuned_2/train/ --save_dir /no_save/ --eval --epochs 1 --critic_scores_path /mnt/t-qingru/RLHF/critic_scores/finetuned_e10_batch4/ --model_path /mnt/t-qingru/RLHF/outputs/critic/base_finetuned_temp0.6_seq20_3/final_checkpoint/